### ISSUE TITLE
Problema con l'apertura dei file JSON su Windows

### ISSUE THREAD

**Issue by leotodisco** [carlovend/CADOCS_II#1]
## Expected Behavior
Ci si aspetta che quando si apra un JSON, si possano leggere i suoi campi senza incappare in eccezioni

## Current Behavior
Quando si apre un JSON su Windows viene lanciata un'eccezione

## Possible Solution
Una possibile soluzione è quella di specificare il corretto encoding, e.g. "utf8"

## Steps to Reproduce
1. Effettuare il log in a CADOCS II
2. Chiedere a CADOCS II di trovare gli smells in una repository
3. A questo punto verrà lanciata un'eccezione quando vengono aperti i risultati di CS_DETECTOR

## Context (Environment)
L'ambiente affetto è una macchina con Windows 10/Windows 11.

## Detailed Description
Ciò che si intende fare è aggiungere l'algoritmo di encoding quando si aprono i file JSON nella componente:
> cadocs_messages.py

## Possible Implementation
Esempio:
```python
 with open('src/community_smells_it.json', encoding="utf8")

**Comment by benedettoscala** [comment]
The issue was resolved in the commit #https://github.com/carlovend/CADOCS_II/commit/1d40a0d37cf09968bfe22a153a98b42cbb1f6f4e
